# Algebra Lineal
## Scott. Cap.3 Sistemas lineales pag.35-37

### 3.1 Gaussian elimination
Un sistema lineal de n ecuaciones en n variables reales toma la forma
$a_{11}x_1+a_{12}x_2+...a_{1n}x_n= f_1$
$a_{21}x_1+a_{22}x_2+...a_{2n}x_n= f_2$
....
$a_{n1}x_1+a_{n2}x_2+...a_{nn}x_n= f_n$

.... 

In [9]:
import numpy as np
import sympy as sy
import matplotlib.pyplot as plt

#para que me de matrices 3x3 aleatorias A y B con enteros demaximo valor 10 
A=np.random.randint(10, size=(3,3))
B=np.random.randint(10, size=(3,3))
print(A)
print(B)

#paso 1: ahora deberiamos hacerle gauss jordan para reducir la matriz a una triangular superior
#paso 2: luego hacer la sustitución para atras para encontrar las x

[[2 5 1]
 [5 9 8]
 [7 7 8]]
[[5 1 3]
 [5 5 3]
 [7 9 4]]


Notación que puede ser util en codigo: ejemplo
A[2,0:] Te da toda la fila es decir [A[2,0],A[2,1],A[2,2]
