Para un sistema lineal de ecuaciones descritas por la matriz de coeficientes A, vector de variables X y las salidas en vector F este se describe por el producto de matrices AX=F.
Reduciendo la matriz por reducción de renglones hasta obtener una matriz triangular superior U y entonces AX=F se convierte en UX=G, resolver para X ya es más sencillo y se hace a traves de la sustitución hacia atras, entonces tenemos el valor de las variables X y nuestro sistema lineal resuelto.

El algoritmo viene descrito en el capitulo 3, seccion 3.1 del Scott. Numerical Analysis. 


ESCRIBIENDO $AX=F$

In [25]:
#para trabajar con vectores y matrices es el numpy
#para trabajar con valores simbolicos es el sympy
import numpy as np
import sympy as sy

x,y,z,w= sy.symbols('x,y,z,w')

X= np.array([x,y,z,w])
#Inserta los coeficientes de cada ecuacion: los n elementos de la matriz A por fila
A= np.array([[1,1,0,0],[1,0,0,1],[0,0,1,1],[0,1,1,0]])
#insertar las igualdades de cada ecuacion: los n elementos del vector F
F= np.array([6,2,6,8])

print(A)
print(X)
print(F)

[[1 1 0 0]
 [1 0 0 1]
 [0 0 1 1]
 [0 1 1 0]]
[x y z w]
[6 2 6 8]


OBTENCION DE $U$ y $G$

In [26]:
def triang(A,F):
    #copiamos A y F para no usar originales
    U = np.copy(A)
    G = np.copy(F)
    #saca el tamaño del vector F y se lo asigna a n, n es el numero de elementos por fila y columna
    n = F.size
    
    for j in range(n-1):
        for i in range(j+1,n):
            M =U[i,j]/U[j,j]
            #j: hace que j recorra toda la fila
            U[i,j:] = U[i,j:] - (M*U[j,j:])
            G[i]= G[i] - (M*G[j])
    return U,G

#la funcion triang devuelve dos valores, 0 es U y 1 es G por eso se escribe [0] y [1] para acceder al return 0 y return 1            
U=triang(A,F)[0]
print(U)
G=triang(A,F)[1]
print(G)

[[ 1  1  0  0]
 [ 0 -1  0  1]
 [ 0  0  1  1]
 [ 0  0  0  0]]
[ 6 -4  6 -2]


SUSTITUCION PARA ATRAS PARA OBTENCION DE SOLUCION X

In [27]:
def sol(U,G):
    n = G.size
    #inicializa vector x de tamaño n con ceros 
    x = np.zeros(n)
    a = 0
    for i in reversed(range(n)):
        if i == n-1:
            x[i] = (G[i])/(U[i,i])
            continue
        else:
            for j in range (i+1,n):
                a += U[i,j]*x[j]
            x[i] = (G[i]/U[i,i]) - (1/U[i,i])*a
            a = 0
    return x

In [28]:
sol(U,G)


C:\Users\esme_\AppData\Local\Temp\ipykernel_17092\2049148744.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = (G[i])/(U[i,i])
C:\Users\esme_\AppData\Local\Temp\ipykernel_17092\2049148744.py:12: RuntimeWarning: invalid value encountered in scalar multiply
  a += U[i,j]*x[j]


array([ nan,  nan,  inf, -inf])