Para un sistema lineal de ecuaciones descritas por la matriz de coeficientes A, vector de variables X y las salidas en vector F este se describe por el producto de matrices AX=F.
Reduciendo la matriz por reducción de renglones hasta obtener una matriz triangular superior U y entonces AX=F se convierte en UX=G, resolver para X ya es más sencillo y se hace a traves de la sustitución hacia atras, entonces tenemos el valor de las variables X y nuestro sistema lineal resuelto.

El algoritmo viene descrito en el capitulo 3, seccion 3.1 del Scott. Numerical Analysis. 


ESCRIBIENDO $AX=F$

In [5]:
#para trabajar con vectores y matrices es el numpy
#para trabajar con valores simbolicos es el sympy
import numpy as np
import sympy as sy

x,y,z= sy.symbols('x,y,z')

X= np.array([x,y,z])
#Inserta los coeficientes de cada ecuacion: los n elementos de la matriz A por fila
A= np.array([[2,4,6],[4,5,6],[3,1,-2]])
#insertar las igualdades de cada ecuacion: los n elementos del vector F
F= np.array([18,24,4])

print(A)
print(X)
print(F)

[[ 2  4  6]
 [ 4  5  6]
 [ 3  1 -2]]
[x y z]
[18 24  4]


OBTENCION DE $U$ y $G$

In [6]:
def triang(A,F):
    #copiamos A y F para no usar originales
    U = np.copy(A)
    G = np.copy(F)
    #saca el tamaño del vector F y se lo asigna a n, n es el numero de elementos por fila y columna
    n = F.size
    
    for j in range(n-1):
        for i in range(j+1,n):
            M =U[i,j]/U[j,j]
            #j: hace que j recorra toda la fila
            U[i,j:] = U[i,j:] - (M*U[j,j:])
            G[i]= G[i] - (M*G[j])
    return U,G

#la funcion triang devuelve dos valores, 0 es U y 1 es G por eso se escribe [0] y [1] para acceder al return 0 y return 1            
U=triang(A,F)[0]
print(U)
G=triang(A,F)[1]
print(G)

[[ 2  4  6]
 [ 0 -3 -6]
 [ 0  0 -1]]
[ 18 -12  -3]


SUSTITUCION PARA ATRAS PARA OBTENCION DE SOLUCION X

In [7]:
def sol(U,G):
    n = G.size
    #inicializa vector x de tamaño n con ceros 
    x = np.zeros(n)
    a = 0
    for i in reversed(range(n)):
        if i == n-1:
            x[i] = (G[i])/(U[i,i])
            continue
        else:
            for j in range (i+1,n):
                a += U[i,j]*x[j]
            x[i] = (G[i]/U[i,i]) - (1/U[i,i])*a
            a = 0
    return x

In [8]:
sol(U,G)


array([ 4., -2.,  3.])